export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',

    ADD_NEW_CATEGORIES_REQUEST: 'ADD_NEW_CATEGORIES_REQUEST',
    ADD_NEW_CATEGORIES_SUCCESS: 'ADD_NEW_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORIES_FAILURE: 'ADD_NEW_CATEGORIES_FAILURE',

    UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',

    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE',

}

export const brandConstants = {
    GET_ALL_BRANDS_REQUEST: 'GET_ALL_BRANDS_REQUEST',
    GET_ALL_BRANDS_SUCCESS: 'GET_ALL_BRANDS_SUCCESS',
    GET_ALL_BRANDS_FAILURE: 'GET_ALL_BRANDS_FAILURE',

    ADD_NEW_BRANDS_REQUEST: 'ADD_NEW_BRANDS_REQUEST',
    ADD_NEW_BRANDS_SUCCESS: 'ADD_NEW_BRANDS_SUCCESS',
    ADD_NEW_BRANDS_FAILURE: 'ADD_NEW_BRANDS_FAILURE',

    UPDATE_BRANDS_REQUEST: 'UPDATE_BRANDS_REQUEST',
    UPDATE_BRANDS_SUCCESS: 'UPDATE_BRANDS_SUCCESS',
    UPDATE_BRANDS_FAILURE: 'UPDATE_BRANDS_FAILURE',

    DELETE_BRANDS_REQUEST: 'DELETE_BRANDS_REQUEST',
    DELETE_BRANDS_SUCCESS: 'DELETE_BRANDS_SUCCESS',
    DELETE_BRANDS_FAILURE: 'DELETE_BRANDS_FAILURE',

}

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',

    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",


    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

}

export const initialDataConstants = {
    GET_INITIAL_DATA_REQUEST: 'GET_INITIAL_DATA_REQUEST',
    GET_INITIAL_DATA_SUCCESS: 'GET_INITIAL_DATA_SUCCESS',
    GET_INITIAL_DATA_FAILURE: 'GET_INITIAL_DATA_FAILURE',

}

export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE',
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};

export const accountConstants = {
    GET_ALL_ACCOUNT_REQUEST: 'GET_ALL_ACCOUNT_REQUEST',
    GET_ALL_ACCOUNT_SUCCESS: 'GET_ALL_ACCOUNT_SUCCESS',
    GET_ALL_ACCOUNT_FAILURE: 'GET_ALL_ACCOUNT_FAILURE',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    GET_ORDERS_ACCOUNT_REQUEST: 'GET_ORDERS_ACCOUNT_REQUEST',
    GET_ORDERS_ACCOUNT_SUCCESS: 'GET_ORDERS_ACCOUNT_SUCCESS',
    GET_ORDERS_ACCOUNT_FAILURE: 'GET_ORDERS_ACCOUNT_FAILURE',
}

export const supplierConstants = {
    GET_ALL_SUPPLIER_REQUEST: 'GET_ALL_SUPPLIER_REQUEST',
    GET_ALL_SUPPLIER_SUCCESS: 'GET_ALL_SUPPLIER_SUCCESS',
    GET_ALL_SUPPLIER_FAILURE: 'GET_ALL_SUPPLIER_FAILURE',

    CREATE_SUPPLIER_REQUEST: 'CREATE_SUPPLIER_REQUEST',
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_FAILURE: 'CREATE_SUPPLIER_FAILURE',

    UPDATE_SUPPLIER_REQUEST: 'UPDATE_SUPPLIER_REQUEST',
    UPDATE_SUPPLIER_SUCCESS: 'UPDATE_SUPPLIER_SUCCESS',
    UPDATE_SUPPLIER_FAILURE: 'UPDATE_SUPPLIER_FAILURE',
}

export const receiptConstants = {
    GET_ALL_RECEIPT_REQUEST: 'GET_ALL_RECEIPT_REQUEST',
    GET_ALL_RECEIPT_SUCCESS: 'GET_ALL_RECEIPT_SUCCESS',
    GET_ALL_RECEIPT_FAILURE: 'GET_ALL_RECEIPT_FAILURE',

    CREATE_RECEIPT_REQUEST: 'CREATE_RECEIPT_REQUEST',
    CREATE_RECEIPT_SUCCESS: 'CREATE_RECEIPT_SUCCESS',
    CREATE_RECEIPT_FAILURE: 'CREATE_RECEIPT_FAILURE',
}

